export const LOADING_EVENTS = 'LOADING_EVENTS'
export const MORELOADING_EVENTS = 'MORELOADING_EVENTS'
export const ADD_EVENTS = 'ADD_EVENTS'
export const MORE_EVENTS = 'MORE_EVENTS'
export const FAILED_EVENTS = 'FAILED_EVENTS'

export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'