export const LOADING_EVENTS = 'LOADING_EVENTS'
export const ADD_EVENTS = 'ADD_EVENTS'
export const FAILED_EVENTS = 'FAILED_EVENTS'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'

export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const NOTIFY_MESS = 'NOTIFY_MESS'
export const CLEAR_MESS = 'CLEAR_MESS'

export const UPDATE_IMAGE = 'UPDATE_IMAGE'